### ISSUE TITLE
MultiLocationAlertCondition panic index out of range

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-newrelic#697]
### What happened?

The following program yields this panic, could be upstream:

```
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) panic: runtime error: index out of range [3] with length 1
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) goroutine 59 [running]:
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/newrelic/terraform-provider-newrelic/v2/newrelic.getMonitorID({0x1400013bb60?, 0x102e59d4a?})
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/work/pulumi-newrelic/pulumi-newrelic/upstream/newrelic/resource_helpers_synthetics.go:460 +0x84
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandMultiLocationSyntheticsCondition(0x10?)
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/work/pulumi-newrelic/pulumi-newrelic/upstream/newrelic/structures_newrelic_synthetics_multilocation_alert_condition.go:31 +0x288
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicSyntheticsMultiLocationAlertConditionCreate({0x1034c2248, 0x1400025ebd0}, 0x0?, {0x103249340?, 0x1400056c440?})
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/work/pulumi-newrelic/pulumi-newrelic/upstream/newrelic/resource_newrelic_synthetics_multilocation_alert_condition.go:110 +0x90
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140000f2c40, {0x1034c21a0, 0x1400019e630}, 0xd?, {0x103249340, 0x1400056c440})
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240229143312-4f60ee4e2975/helper/schema/resource.go:783 +0xe8
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140000f2c40, {0x1034c21a0, 0x1400019e630}, 0x0, 0x14000434a80, {0x103249340, 0x1400056c440})
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240229143312-4f60ee4e2975/helper/schema/resource.go:914 +0x86c
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x1400080c660?, {0x0?, 0x102e9756b?, 0x31?}}, {0x1034c21a0, 0x1400019e630}, {0x102e9756b, 0x31}, {0x0?, 0x0}, ...)
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.78.0/pkg/tfshim/sdk-v2/provider.go:122 +0x148
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x14000a01980, {0x1034c21a0?, 0x14000444ea0?}, 0x140002f8eb0)
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.78.0/pkg/tfbridge/provider.go:1055 +0x67c
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x1034c21a0, 0x14000444ea0}, {0x1033aeae0?, 0x140002f8eb0})
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.111.1/proto/go/provider_grpc.pb.go:593 +0x74
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1034c21a0, 0x14000444b10}, {0x1033aeae0, 0x140002f8eb0}, 0x140001514e0, 0x14000554ac8)
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x1034623c0?, 0x14000a01980}, {0x1034c21a0, 0x14000444b10}, 0x14000712480, 0x140007161e0)
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.111.1/proto/go/provider_grpc.pb.go:595 +0x12c
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) google.golang.org/grpc.(*Server).processUnaryRPC(0x14000282a00, {0x1034c21a0, 0x14000444a80}, {0x1034cc320, 0x140001024e0}, 0x14000110fc0, 0x140002682a0, 0x10406c560, 0x0)
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.0/server.go:1383 +0xb8c
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) google.golang.org/grpc.(*Server).handleStream(0x14000282a00, {0x1034cc320, 0x140001024e0}, 0x14000110fc0)
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.0/server.go:1794 +0xc70
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) google.golang.org/grpc.(*Server).serveStreams.func2.1()
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.0/server.go:1027 +0x8c
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 100
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s)    /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.0/server.go:1038 +0x150
 +  newrelic:synthetics:MultiLocationAlertCondition newrelic_multilocationalertcondition creating (0s) error: error reading from server: EOF
 +  newrelic:synthetics:MultiLocationAlertCondition newrelic_multilocationalertcondition **creating failed** error: error reading from server: EOF
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev creating (1s) error: update failed
 +  pulumi:pulumi:Stack synthetics_multilocationalertconditionsHdfILQm1FTB-dev **creating failed (0.52s)** 1 error; 30 messages
Policies:
    ✅ pulumi-internal-policies@v0.0.6

Diagnostics:
  pulumi:pulumi:Stack (synthetics_multilocationalertconditionsHdfILQm1FTB-dev):
    panic: runtime error: index out of range [3] with length 1
    goroutine 59 [running]:
    github.com/newrelic/terraform-provider-newrelic/v2/newrelic.getMonitorID({0x1400013bb60?, 0x102e59d4a?})
        /home/runner/work/pulumi-newrelic/pulumi-newrelic/upstream/newrelic/resource_helpers_synthetics.go:460 +0x84
    github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandMultiLocationSyntheticsCondition(0x10?)
        /home/runner/work/pulumi-newrelic/pulumi-newrelic/upstream/newrelic/structures_newrelic_synthetics_multilocation_alert_condition.go:31 +0x288
    github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicSyntheticsMultiLocationAlertConditionCreate({0x1034c2248, 0x1400025ebd0}, 0x0?, {0x103249340?, 0x1400056c440?})
        /home/runner/work/pulumi-newrelic/pulumi-newrelic/upstream/newrelic/resource_newrelic_synthetics_multilocation_alert_condition.go:110 +0x90
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140000f2c40, {0x1034c21a0, 0x1400019e630}, 0xd?, {0x103249340, 0x1400056c440})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240229143312-4f60ee4e2975/helper/schema/resource.go:783 +0xe8
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140000f2c40, {0x1034c21a0, 0x1400019e630}, 0x0, 0x14000434a80, {0x103249340, 0x1400056c440})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240229143312-4f60ee4e2975/helper/schema/resource.go:914 +0x86c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x1400080c660?, {0x0?, 0x102e9756b?, 0x31?}}, {0x1034c21a0, 0x1400019e630}, {0x102e9756b, 0x31}, {0x0?, 0x0}, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.78.0/pkg/tfshim/sdk-v2/provider.go:122 +0x148
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x14000a01980, {0x1034c21a0?, 0x14000444ea0?}, 0x140002f8eb0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.78.0/pkg/tfbridge/provider.go:1055 +0x67c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x1034c21a0, 0x14000444ea0}, {0x1033aeae0?, 0x140002f8eb0})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.111.1/proto/go/provider_grpc.pb.go:593 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1034c21a0, 0x14000444b10}, {0x1033aeae0, 0x140002f8eb0}, 0x140001514e0, 0x14000554ac8)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x1034623c0?, 0x14000a01980}, {0x1034c21a0, 0x14000444b10}, 0x14000712480, 0x140007161e0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.111.1/proto/go/provider_grpc.pb.go:595 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x14000282a00, {0x1034c21a0, 0x14000444a80}, {0x1034cc320, 0x140001024e0}, 0x14000110fc0, 0x140002682a0, 0x10406c560, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.0/server.go:1383 +0xb8c
    google.golang.org/grpc.(*Server).handleStream(0x14000282a00, {0x1034cc320, 0x140001024e0}, 0x14000110fc0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.0/server.go:1794 +0xc70
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.0/server.go:1027 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 100
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.0/server.go:1038 +0x150

    error: update failed

  newrelic:synthetics:MultiLocationAlertCondition (newrelic_multilocationalertcondition):
    error: error reading from server: EOF
```

### Example

```yaml
name: synthetics_multilocationalertconditionsHdfILQm1FTB
runtime: yaml
resources:
  newrelic_multilocationalertcondition:
    properties:
      critical:
        threshold: 5
      enabled: true
      entities:
        - synthetics-monitor-id
      policyId: 12345678
      violationTimeLimitSeconds: 3600
    type: newrelic:synthetics:MultiLocationAlertCondition

```

### Output of `pulumi about`

```
CLI          
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME      VERSION
newrelic  unknown
yaml      unknown

Host     
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in yaml

Current Stack: pulumi/synthetics_multilocationalertconditionsHdfILQm1FTB/dev

TYPE                       URN
pulumi:pulumi:Stack        urn:pulumi:dev::synthetics_multilocationalertconditionsHdfILQm1FTB::pulumi:pulumi:Stack::synthetics_multilocationalertconditionsHdfILQm1FTB-dev
pulumi:providers:newrelic  urn:pulumi:dev::synthetics_multilocationalertconditionsHdfILQm1FTB::pulumi:providers:newrelic::default


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/venelin-pulumi-corp
User           venelin-pulumi-corp
Organizations  venelin-pulumi-corp, demo, pulumi
Token type     personal

No dependencies found
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
So....while this should not panic, and error instead, this is definitely an upstream panic.

However - this code is incomplete. You'll need to add a `policy` and a `monitor` to query. When there is no valid `monitor.id` to query, the panic gets triggered.

I'll file an upstream bug. However, this being a legacy resource, they may not work on a fix or accept a patch.

For completeness sake:

To avoid hitting this panic, ensure you have a valid `AlertPolicy` and `Monitor` resource in addition to the `MultiLocationAlertCondition`. [Link to Basic Example](https://www.pulumi.com/registry/packages/newrelic/api-docs/synthetics/multilocationalertcondition/#example-usage)

**Comment by guineveresaenger** [comment]
update: several upstream issues report this behavior but the panic is never addressed; users are directed to use the correct monitor ID:
https://github.com/newrelic/terraform-provider-newrelic/issues/2003
https://github.com/newrelic/terraform-provider-newrelic/issues/2234

**Comment by guineveresaenger** [comment]
Filed https://github.com/newrelic/terraform-provider-newrelic/issues/2631.

**Comment by guineveresaenger** [comment]
Opened https://github.com/newrelic/terraform-provider-newrelic/pull/2632 to address.

**Comment by guineveresaenger** [comment]
Removing the p1 here because there's a clear path forward to avoid the panic.

**Comment by guineveresaenger** [comment]
Fixed via https://github.com/newrelic/terraform-provider-newrelic/issues/2631 and most recent version of this provider.
